CREATE TABLE IF NOT EXISTS "ENRUTAMIENTO_LINEA_PAGO" (
    "ID_ENRUTAMIENTO" UUID PRIMARY KEY,
    "ID_EVENTO_ORIGEN" UUID,
    "ID_LOTE" UUID NOT NULL,
    "ID_LINEA" UUID NOT NULL UNIQUE,
    "ID_CORRELACION" UUID NOT NULL,
    "NUMERO_SECUENCIA" INTEGER,
    "RUC_EMPRESA" VARCHAR(20),
    "NUMERO_CUENTA_MATRIZ" VARCHAR(40),
    "ID_FONDEO_CORE" VARCHAR(80),
    "IDENTIFICACION_BENEFICIARIO" VARCHAR(30),
    "NOMBRE_BENEFICIARIO" VARCHAR(120),
    "NUMERO_CUENTA_DESTINO" VARCHAR(40),
    "CODIGO_ENRUTAMIENTO" VARCHAR(10),
    "MONTO" NUMERIC(18, 2),
    "MONEDA" VARCHAR(3),
    "REFERENCIA" VARCHAR(140),
    "EMAIL_NOTIFICACION" VARCHAR(120),
    "TIPO_ENRUTAMIENTO" VARCHAR(20),
    "ESTADO" VARCHAR(30) NOT NULL,
    "FECHA_CREACION" TIMESTAMPTZ NOT NULL,
    "FECHA_ACTUALIZACION" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "DECISION_ENRUTAMIENTO" (
    "ID_DECISION" UUID PRIMARY KEY,
    "ID_LINEA" UUID NOT NULL UNIQUE,
    "ID_LOTE" UUID NOT NULL,
    "TIPO_ENRUTAMIENTO" VARCHAR(20) NOT NULL,
    "CODIGO_ENRUTAMIENTO" VARCHAR(10) NOT NULL,
    "NOMBRE_INSTITUCION_DESTINO" VARCHAR(120),
    "ID_EVENTO_PUBLICADO" UUID NOT NULL,
    "CLAVE_ENRUTAMIENTO_PUBLICADA" VARCHAR(120) NOT NULL,
    "FECHA_DECISION" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "ERROR_ENRUTAMIENTO" (
    "ID_ERROR_ENRUTAMIENTO" UUID PRIMARY KEY,
    "ID_LINEA" UUID NOT NULL UNIQUE,
    "ID_LOTE" UUID NOT NULL,
    "ID_EVENTO_ORIGEN" UUID,
    "CODIGO_RECHAZO" VARCHAR(60) NOT NULL,
    "MOTIVO_RECHAZO" VARCHAR(500) NOT NULL,
    "ID_EVENTO_PUBLICADO" UUID NOT NULL,
    "CLAVE_ENRUTAMIENTO_PUBLICADA" VARCHAR(120) NOT NULL,
    "FECHA_CREACION" TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS "IDX_ENRUTAMIENTO_LINEA_LOTE"
    ON "ENRUTAMIENTO_LINEA_PAGO" ("ID_LOTE");

CREATE INDEX IF NOT EXISTS "IDX_ENRUTAMIENTO_CODIGO"
    ON "ENRUTAMIENTO_LINEA_PAGO" ("CODIGO_ENRUTAMIENTO");

CREATE INDEX IF NOT EXISTS "IDX_DECISION_ENRUTAMIENTO_LOTE"
    ON "DECISION_ENRUTAMIENTO" ("ID_LOTE");

CREATE INDEX IF NOT EXISTS "IDX_DECISION_TIPO_ENRUTAMIENTO"
    ON "DECISION_ENRUTAMIENTO" ("TIPO_ENRUTAMIENTO");

CREATE INDEX IF NOT EXISTS "IDX_ERROR_ENRUTAMIENTO_LOTE"
    ON "ERROR_ENRUTAMIENTO" ("ID_LOTE");
